diff output/output1.txt std/E.1.diff
diff output/output2.txt std/E.2.diff
diff output/output3.txt std/E.3.diff
diff output/output4.txt std/E.4.diff
diff output/output5.txt std/E.5.diff
diff output/output6.txt std/E.6.diff
diff output/output7.txt std/E.7.diff
diff output/output8.txt std/E.8.diff
diff output/output9.txt std/E.9.diff
diff output/output10.txt std/E.10.diff
diff output/output11.txt std/E.11.diff
diff output/output12.txt std/E.12.diff
diff output/output13.txt std/E.13.diff
diff output/output14.txt std/E.14.diff
diff output/output15.txt std/E.15.diff
diff output/output16.txt std/E.16.diff
