./run < std/E.1.dat > output/output1.txt
./run < std/E.2.dat > output/output2.txt
./run < std/E.3.dat > output/output3.txt
./run < std/E.4.dat > output/output4.txt
./run < std/E.5.dat > output/output5.txt
./run < std/E.6.dat > output/output6.txt
./run < std/E.7.dat > output/output7.txt
./run < std/E.8.dat > output/output8.txt
./run < std/E.9.dat > output/output9.txt
./run < std/E.10.dat > output/output10.txt
./run < std/E.11.dat > output/output11.txt
./run < std/E.12.dat > output/output12.txt
./run < std/E.13.dat > output/output13.txt
./run < std/E.14.dat > output/output14.txt
./run < std/E.15.dat > output/output15.txt
./run < std/E.16.dat > output/output16.txt
